version: '3.4'

services:
  dtf_message_bot:
    image: ${DOCKER_REGISTRY-}dtfmessagebot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-volume:/data/db

volumes:
  mongo-volume: