name: CI

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.1.0
        with:
          key: ${{ secrets.VM_SSH_KEY }}
          known_hosts: ${{ secrets.VM_SSH_KNOWN_HOSTS }}

      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE
          echo '${{ secrets.APP_SECRETS_JSON }}' > appsettings.secrets.json
          DOCKER_HOST="ssh://root@${{ secrets.VM_HOST }}" docker-compose up -d --build

      - name: Send telegram notification
        uses: appleboy/telegram-action@v0.0.8
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: format('**{0}** just deployed [new changes]({1})', github.actor, github.event.compare)
          format: markdown
