name: Telegram notifications

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
      - prod

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send master push notification
      if: github.ref == "master" && github.event_name == "push"
      uses: appleboy/telegram-action@v0.0.8
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: format('<b>{0}</b> pushed to <b>{1}</b>\n<i>{2}</i>', github.actor, github.ref, join(github.event.commits.*.message, '\n'))
        format: html
    - name: Send new PR notification
      if: github.base_ref == "master" && github.event_name == "pull_request" && github.event.action == "opened"
      uses: appleboy/telegram-action@v0.0.8
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: format('New <a href="https://github.com/{1}/pull/{0}">PR #{0}</a> by <b>{2}</b>: <i>{3}</i>', github.event.number, github.repository, github.actor, github.event.title)
        format: html
    - name: Send prod PR notification
      if: github.base_ref == "prod" && github.event_name == "pull_request" && github.event.action == "opened"
      uses: appleboy/telegram-action@v0.0.8
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: format('New deploy <a href="https://github.com/{1}/pull/{0}">PR #{0}</a> by <b>{2}</b>: <i>{3}</i>', github.event.number, github.repository, github.actor, github.event.title)
        format: html
